### ISSUE TITLE
c00: 编程用的基本工具

### ISSUE THREAD

**Issue by kiochan** [kiochan/react-tutor-202307#1]
时间
2023-07-01 14:00 ~ 15:00 (多伦多)
2023-07-01 19:00 ~ 20:00 (英国)
2023-07-01 20:00 ~ 21:00 (欧洲西部)
2023-07-02 02:00 ~ 03:00 (台北)

在这堂课会学到：
1. 编辑器 vscode 的安装
2. 如何使用 git 进行版本管理

相关链接：
1. [VSCode](https://code.visualstudio.com/)
2. [Git 版本管理工具](https://git-scm.com/)
3. [Github Desktop - 由 Github 提供的Git图形工具](https://desktop.github.com/)

**Comment by kiochan** [comment]
@YueMeiHong @DurdaeEstel @ZhaoFufen @LauranceLi 
看一下时间是否合适，如果认为合适可以给这条信息点赞。

**Comment by ZhaoFufen** [comment]
早点迟点都可以, 台北会不会太晚了?

**Comment by YueMeiHong** [comment]
好耶

**Comment by kiochan** [comment]
> 早点迟点都可以, 台北会不会太晚了?

有道理，询问一下 @LauranceLi 的意见

**Comment by kiochan** [comment]
> > 早点迟点都可以, 台北会不会太晚了?
> 
> 有道理，询问一下 @LauranceLi 的意见

囷鹿觉得OK

**Comment by kiochan** [comment]
课程完毕，有问题请开新的issue，并且 assign 给我。
