### ISSUE TITLE
c06: 从头学一遍怎么写TS程序

### ISSUE THREAD

**Issue by kiochan** [kiochan/react-tutor-202307#47]
# 时间
2023-07-17 14:00 ~ 15:00 (多伦多)
2023-07-17 19:00 ~ 20:00 (英国)
2023-07-17 20:00 ~ 21:00 (欧洲西部)
2023-07-18 02:00 ~ 03:00 (台北)

# 目的
梳理之前的知识点

# 在这堂课会学到

* c02 到 c05 的内容

# 之前相关课程链接
#2 #3 #22 #24 #41

**Comment by kiochan** [comment]
点赞表示你会来
@YueMeiHong @DurdaeEstel @ZhaoFufen @LauranceLi

**Comment by YueMeiHong** [comment]
@kiochan 记得录屏，我可能来不了，作息太阴间了ʚෆɞ(˘ᵋॢ ˘♡)˚

**Comment by kiochan** [comment]
此课程因为没人来所以关闭，大家重新商量日期。
