### ISSUE TITLE
重新商讨上课时间

### ISSUE THREAD

**Issue by kiochan** [kiochan/react-tutor-202307#48]
重新商讨上课时间，因为课程 #47 没人来，所以咱们重新商讨下上课时间吧。

大家把自己可行的时间段说一下哦。

**Comment by YueMeiHong** [comment]
最近作息大概国内凌晨6：00起来19:00到20:00睡觉，中间我都行。特别重复是换算的**国内时间**

**Comment by kiochan** [comment]
@YueMeiHong  `UTC 23:00 - 12:00` `每天`

其他人呢？ @DurdaeEstel @ZhaoFufen @LauranceLi

**Comment by DurdaeEstel** [comment]
我都可以嗷，提前一天这样确定就行，基本随时能在

**Comment by ZhaoFufen** [comment]
uk时间16-21都可以。

DurdaeEstel ***@***.***> 于 2023年7月19日周三 18:15写道：

**Comment by ZhaoFufen** [comment]
uk时间16-21都可以

祈緒ちゃん - Kiochan ***@***.***> 于 2023年7月18日周二 02:39写道：

**Comment by kiochan** [comment]
@YueMeiHong  `UTC 22:00 - 11:00 每天`
@DurdaeEstel  `UTC 00:00 - 00:00 每天`
@ZhaoFufen  `UTC 15:00 - 20:00 每天`

还剩下 @LauranceLi  需要确定下

**Comment by LauranceLi** [comment]
我国内时间除了2130-0000都有空。

**Comment by kiochan** [comment]
@YueMeiHong  `UTC 22:00 - 11:00 每天`
@DurdaeEstel  `UTC 00:00 - 00:00 每天`
@ZhaoFufen  `UTC 15:00 - 20:00 每天`
@LauranceLi `UTC 16:00 - 13:30 每天`

```
  000000000011111111112222
  012345678901234567890123
M XXXXXXXXXXXX          XX
D XXXXXXXXXXXXXXXXXXXXXXXX
Z                XXXXXX  
L XXXXXXXXXXXXXXX  XXXXXXX
```

**Comment by kiochan** [comment]
尕牙和妹红无重合时间 需要解决冲突
@ZhaoFufen  @YueMeiHong

**Comment by YueMeiHong** [comment]
我UTC+0的话是21：00到第二天0:00左右

**Comment by kiochan** [comment]
@YueMeiHong `UTC 21:00 - 00:00 每天`
@DurdaeEstel `UTC 00:00 - 00:00 每天`
@ZhaoFufen `UTC 16:00 - 21:00 每天`
@LauranceLi `UTC 17:00 - 15:30 每天`

```
  000000000011111111112222
  012345678901234567890123
M                      XXX
D XXXXXXXXXXXXXXXXXXXXXXXX
Z                XXXXXX   
L XXXXXXXXXXXXXXX  XXXXXXX
```

@ZhaoFufen  @YueMeiHong 
依然没有重合时间

**Comment by YueMeiHong** [comment]
20:00-12:00，之前没说清楚上午下午，这次应该没问题了。4+12,16小时在线

**Comment by kiochan** [comment]
@YueMeiHong  根据妹红所说 暂时先不考虑妹红

@DurdaeEstel `UTC 00:00 - 00:00 每天`
@ZhaoFufen `UTC 16:00 - 21:00 每天`
@LauranceLi `UTC 17:00 - 15:30 每天`

```
  000000000011111111112222
  012345678901234567890123
D XXXXXXXXXXXXXXXXXOOOOXXX
Z                XXOOOO   
L XXXXXXXXXXXXXXX  OOOOXXX
```

咱们的时间点如下：

17:00 ~ 20:00 (UTC)
12:00 ~ 17:00 (多伦多)
18:00 ~ 22:00 (英国)
19:00 ~ 23:00 (欧洲西部)
01:00 ~ 05:00 (台北)

那么下次上课可以从以下时间开始（留出30分钟的缓冲时间）：

2023-07-21 17:30 ~ 18:30 (UTC)
2023-07-21 12:30 ~ 13:30 (多伦多)
2023-07-21 18:30 ~ 19:30 (英国)
2023-07-21 19:30 ~ 20:30 (欧洲西部)
2023-07-22 01:30 ~ 02:30 (台北)

<del>确认请点赞本条信息</del>

**Comment by kiochan** [comment]
@YueMeiHong 根据妹红所说 暂时先不考虑妹红
@ZhaoFufen 
```
@ZhaoFufen 15:08:53
@@kiochan 
emmmm ... 
香香, 不用考虑我的时间. 我最近要忙论文的事情, 所以时间比较烦.

@ZhaoFufen 15:09:24
而且你可以给一些react的api文档, 我自己看看, 有什么不明白的问问你, 应该也差不多能跟上进度的.
```

@DurdaeEstel UTC 00:00 - 00:00 每天
@LauranceLi UTC 17:00 - 15:30 每天

```
  000000000011111111112222
  012345678901234567890123
D XXXXXXXXXXXXXXXXXOOOOXXX
L XXXXXXXXXXXXXXX  OOOOXXX
```
咱们的时间点如下：

17:00 ~ 20:00 (UTC)
12:00 ~ 17:00 (多伦多)
18:00 ~ 22:00 (英国)
19:00 ~ 23:00 (欧洲西部)
01:00 ~ 05:00 (台北)

那么下次上课可以从以下时间开始（留出30分钟的缓冲时间）：

2023-07-21 17:30 ~ 18:30 (UTC)
2023-07-21 12:30 ~ 13:30 (多伦多)
2023-07-21 18:30 ~ 19:30 (英国)
2023-07-21 19:30 ~ 20:30 (欧洲西部)
2023-07-22 01:30 ~ 02:30 (台北)

确认请点赞本条信息

**Comment by kiochan** [comment]
时间已确定
