### ISSUE TITLE
c00: 作业

### ISSUE THREAD

**Issue by kiochan** [kiochan/react-tutor-202307#5]
1. 在分支 `c00` 创建一个属于自己的文件夹，请用自己的名字命名
2. 在文件夹下创建一个文档，写一段简短的自我介绍
3. 创建完成后开启一个 issue 让别人在自己的文件中留言
4. 在别人的文件里留言

**Comment by YueMeiHong** [comment]
搞定(◔౪◔)

**Comment by kiochan** [comment]
相关 issues
#6 #8 #7 #9
